### PR TITLE
added max-width to footer

### PR DESCRIPTION
**Pull request by Dburrall**
In Footer.scss I added max-width:100% to make sure the footer is always the length of the page.

### CODE REVIEW

**Comment by aburdiss** [comment]
Hey Dan! Thanks for the PR! For the footer, what I was actually looking for was to constrain the width, so if you're on a triple wide monitor or something like that, the link to the privacy policy lines up with the links in the header instead of being on the edge of the screen. You can reference the way that the header does this, I think it's like a max-width with a margin: auto or something similar! You may have to add a wrapper, but it shouldn't be too hard!

**Comment by Dburrall** [comment]
Sounds good, I'll get that fixed and sent back up tomorrow or Friday,
Thanks!

**Comment by Dburrall** [comment]
I believe I submitted a new PR that fixes the problem. I did it a different
way so let me know if that works or not for you. Thank you!

**Review by aburdiss — APPROVED** [review]

**Comment by aburdiss** [comment]
Thanks for your help on this!

**Comment by Dburrall** [comment]
Glad to help! Looking for my next objective now

**Pull request merged**
